### ISSUE TITLE
This template passed Lighthouse audits only with 55 points for PWA and 11 for Performance

### ISSUE THREAD

**Issue by sh7dm** [vuetifyjs/pwa#10]
![81](https://user-images.githubusercontent.com/19504461/34476308-bb75dfb6-efa0-11e7-92ba-1c14dddf98d4.png)
![82](https://user-images.githubusercontent.com/19504461/34476309-bb98f320-efa0-11e7-87f7-3feb79a4f233.png)
![83](https://user-images.githubusercontent.com/19504461/34476310-bbba3f6c-efa0-11e7-9dc7-0c22fc90f570.png)
![84](https://user-images.githubusercontent.com/19504461/34476311-bbdbe3ec-efa0-11e7-9197-c4bae82d51e6.png)

**Comment by pinicius** [comment]
Hi @nekosaur,
I think you've launched in dev mode (npm run dev)? In this mode, the service worker does not start. You have to build for production (npm run build) and then, use a web server to make it accesible.

Hope it helps you

**Comment by sh7dm** [comment]
Thank you very much! I have built for production and i have Performance = 47 and PWA = 91.
