### ISSUE TITLE
v1 compliant/optimized branch

### ISSUE THREAD

**Issue by paulpv** [vuetifyjs/pwa#11]
I'm a newb to Vue/Vuetify and probably don't have a clue what I am talking about, but from what I can tell Vuetify v1.x appears to be coming out of beta soon, and I am not 100% certain that this template is 100% compliant/optimized for v1.x.

Users that run "vue init vuetifyjs/pwa project" will overwhelmingly want a template optimized to the latest version, which is currently 0.17.6, but how does someone create a template optimized for 1.x?

Once 1.x does ship, surely the template should be ready to go.

"vue init" can reference a branch with the syntax "vue init vuetifyjs/pwa#development my-project", but this repo does not appear to have a v1.x specific branch ready to go.

A branch should be created for a v1 compliant/optimized template so that testers can try out creating a new v1 template vuetify app from scratch.

I imagine that all other templates (esp all of those listed at https://next.vuetifyjs.com/getting-started/quick-start#new-applications) may all benefit from having a v1 branch ready to go.

**Comment by maurop123** [comment]
@paulpv I'm rebooting this template with a fresh fork of PWA from vue-js/templates. The plan is to make a next branch on that repo with 1.0 like webpack has.

I'm going to close this issue so to close this repo, but feel free to checkout the new PWA repo to make sure the next branch is added.
