### ISSUE TITLE
Not run Dev

### ISSUE THREAD

**Issue by joaoeudes7** [vuetifyjs/pwa#2]
Serve not Working....

![image](https://user-images.githubusercontent.com/16367752/36188873-ea3ebb5c-112d-11e8-9423-1f33e88f2213.png)

Node Version = 9.5
Vuetify = next

**Comment by KaelWD** [comment]
Something else is using the port already.

**Comment by joaoeudes7** [comment]
Calm down, did you come to the forehead?

**Comment by KaelWD** [comment]
Did I what now?
