### ISSUE TITLE
<router-view> is missing from App.vue

### ISSUE THREAD

**Issue by HeyOzRamos** [vuetifyjs/pwa#5]
This could be confusing to new developers as it's not immediately obvious how the Hello component is being loaded into the main view (because it isn't).

I added `<router-view>` and it "looks" broken. I could make that component look a bit nicer and make a pull request, but wanted to get a green light before I did so. I could just put that whole thing into a card and turn the links into actions or something basic.
![image](https://user-images.githubusercontent.com/30982892/32570582-5efce59c-c479-11e7-8dd3-d83ce222a9e7.png)

**Comment by nekosaur** [comment]
@maurop123 Any updates on this?

**Comment by maurop123** [comment]
Just merged in this PR to fix this issue: https://github.com/vuetifyjs/pwa/pull/6

Should be working now.
