### ISSUE TITLE
[Bug Report] PWA template doesn't work offline

### ISSUE THREAD

**Issue by Thebigbignooby** [vuetifyjs/pwa#9]
### Versions and Environment
**Vuetify:** 1.0.16
**Vue:** 2.5.2
**Browsers:** Chrome 66.0.3359.117
**OS:** Windows 10

### Steps to reproduce
visit: https://cranky-kalam-a23640.netlify.com
add to home screen on mobile device
turn internet off (disconnect from wifi/mobile-data)
launch the newly added app

### Expected Behavior
app runs normally

### Actual Behavior
"you are offline" browser page

### Reproduction Link
[https://codepen.io/](https://codepen.io/)

### Other comments
Is this a bug, or is there an extra step to do which isn't clearly documented ?

**Comment by KaelWD** [comment]
> on mobile device

Which mobile device? It works fine on android with chrome 65.

**Comment by Thebigbignooby** [comment]
turns out, netlify doesn't redirect to https out of the box. my bad.
